# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.IntegerField(choices=[(0, 'Job'), (1, 'Education'), (2, 'Volunteering')], default=0)),
                ('date_start', models.DateField()),
                ('date_stop', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField()),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cv.Experience')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField()),
                ('main', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['main', 'order', 'level'],
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set([('main', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='experienceactivity',
            unique_together=set([('experience', 'order')]),
        ),
    ]
