# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 18:00
from __future__ import unicode_literals

from django.db import migrations, models


def set_default_orders(apps, schema_editor):
    SocialNetwork = apps.get_model('cv', 'SocialNetwork')

    social_networks = SocialNetwork.objects.all()
    for i, social_network in enumerate(social_networks):
        social_network.order = i
        social_network.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_orders)
    ]
