# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20170628_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienceactivity',
            options={'ordering': ('experience', 'order'), 'verbose_name_plural': 'Experience Activities'},
        ),
        migrations.AlterField(
            model_name='experienceactivity',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
