# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20170628_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('main', 'order', 'level')},
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
