# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 20:47
from __future__ import unicode_literals

from django.db import migrations, models


def set_default_orders(apps, schema_editor):
    Project = apps.get_model('cv', 'Project')

    projects = Project.objects.all()
    for i, project in enumerate(projects):
        project.order = i
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20170628_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_orders)
    ]
