# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20170628_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-date_start',)},
        ),
    ]
