# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20170708_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date_stop',
            field=models.DateField(blank=True, null=True),
        ),
    ]
