# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20170708_2022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experienceactivity',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set([]),
        ),
    ]
