# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 18:46
from __future__ import unicode_literals

import cv.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_auto_20170714_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=cv.models.UploadToPathAndRename('projects/screenshots'))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='cv.Project')),
            ],
            options={
                'verbose_name_plural': 'Project Screenshots',
                'ordering': ('project', 'order'),
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectscreenshot',
            unique_together=set([('project', 'name')]),
        ),
    ]
