# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 06:23
from __future__ import unicode_literals

import cv.decorators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_auto_20170714_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectscreenshot',
            name='image',
            field=models.ImageField(upload_to=cv.decorators.UploadToPathAndRename('cv/projects/screenshots')),
        ),
    ]
