# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 06:40
from __future__ import unicode_literals

import cv.decorators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_auto_20190528_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(null=True, upload_to=cv.decorators.UploadToPathAndRename('cv/resumes/photos'))),
                ('pdf_file', models.FileField(null=True, upload_to=cv.decorators.UploadToPathAndRename('cv/resumes/pdfs'))),
            ],
        ),
    ]
