# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 06:41
from __future__ import unicode_literals

import cv.decorators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=cv.decorators.UploadToPathAndRename('cv/resumes/pdfs')),
        ),
        migrations.AlterField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=cv.decorators.UploadToPathAndRename('cv/resumes/photos')),
        ),
    ]
